const roleData = {
  guxizhao: {
    group: "fuxi",
    name: "顾惜朝",
    age: "青年",
    gender: "男",
    emotion: ["neutral"],
    emotion_intensity: false,
    emotion_max_mapping: 1,
    tags: ["高贵", "磁性", "温柔"],
    desc: "傲气洒脱男",
    example_sentence: "时至今日，你们，可还肯听我一言？",
  },
  yewenzhou: {
    group: "fuxi",
    name: "叶问舟",
    age: "青年",
    gender: "男",
    emotion: ["neutral"],
    emotion_intensity: false,
    emotion_max_mapping: 1,
    tags: ["磁性", "浑厚", "温柔"],
    desc: "温柔男声",
    example_sentence: "这尺八之音。竟能与我如此契合！",
  },
  yexueqing: {
    group: "fuxi",
    name: "叶雪青",
    age: "青年",
    gender: "女",
    emotion: ["neutral"],
    emotion_intensity: false,
    emotion_max_mapping: 1,
    tags: ["温柔", "苏", "纯", "甜"],
    desc: "温柔女声",
    example_sentence: "只要有一丝希望，我都会去试试。",
  },
  maomao: {
    group: "fuxi",
    // name: "卯卯",
    name: "萝莉音",
    age: "少年",
    gender: "女",
    emotion: ["neutral", "happy", "angry", "sad", "fear", "surprise"],
    emotion_intensity: true,
    emotion_max_mapping: 1,
    tags: ["纯", "甜"],
    desc: "看板娘，可爱女声",
    example_sentence: "去吹吹夏日的晚风吧，也许会遇见浪漫呢 ！",
  },
};

export const roleNameMap = Object.entries(roleData).map((item) => {
  return [item[0], item[1].name];
});
